---

- name: Install System Packages dependencies
  ansible.builtin.package:
    name: "{{ system_packages }}"

- name: Enable firewalld
  ansible.builtin.service:
    name: firewalld
    state: started
    enabled: yes

- name: Install Cockpit
  ansible.builtin.include_role:
    name: cockpit
  vars:
    cockpit_packages: "{{ cockpit.cockpit_packages }}"
    cockpit_manage_firewall: "{{ cockpit.cockpit_manage_firewall }}"
  when: cockpit.enabled | bool

- name: Configure /etc/hosts DNS block
  blockinfile:
    dest: /etc/hosts
    content: "{{ lookup('template', 'configs/etc-hosts.j2') }}"
    state: present
    create: yes
    marker: "# {mark} ANSIBLE MANAGED INGRESS BLOCK"
  when: setup_host_dns | bool
