name: Ansible Playbook Workflow
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up CentOS
        uses: actions/checkout@v2
      
      - name: Checkout repository
        uses: actions/checkout@v2
        
    

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Ansible
        run: |
          python -m pip install ansible
          ansible --version
      
      - name: Print PWD
        run: |
          pwd

      - name: Run Ansible playbook
        run: ansible-playbook -i inventory playbooks/install.yml
        env:
          ANSIBLE_HOST_KEY_CHECKING: false
